dataset:
  root_dir: "/kaggle/input/hmdb-dataset/HMDB_simp"
  num_frames: 8          # Number of frames to sample from each video
  frame_size: 224        # Frame resolution (224x224)
  sampling_rate: 32      # Frame sampling rate (higher = more spread out frames)
  categories:
    - brush_hair
    - cartwheel
    - catch
    - chew
    - climb
    - climb_stairs
    - draw_sword
    - eat
    - fencing
    - flic_flac
    - golf
    - handstand
    - kiss
    - pick
    - pour
    - pullup
    - pushup
    - ride_bike
    - shoot_bow
    - shoot_gun
    - situp
    - smile
    - smoke
    - throw
    - wave
training:
  batch_size: 4
  epochs: 10
  learning_rate: 0.0001
  weight_decay: 0.01        # L2 regularization
  early_stopping_patience: 5
  dropout_rate: 0.1
  
  # Advanced training hyperparameters
  gradient_clip_norm: 1.0   # Gradient clipping
  warmup_epochs: 3          # LR warmup epochs
  label_smoothing: 0.1      # Label smoothing factor
  
# Optimizer configuration
optimizer:
  type: "AdamW"             # AdamW, Adam, SGD, RMSprop
  betas: [0.9, 0.999]       # Adam momentum parameters
  eps: 1e-8                 # Numerical stability
  amsgrad: false            # Use AMSGrad variant

# Learning rate scheduler
lr_scheduler:
  type: "StepLR"            # StepLR, CosineAnnealingLR, ReduceLROnPlateau
  step_size: 10             # Epochs between LR reductions
  gamma: 0.1                # LR reduction factor
  
# Data augmentation parameters
augmentation:
  horizontal_flip_prob: 0.5     # Probability of horizontal flip
  brightness_range: 0.3         # Brightness variation range
  contrast_range: 0.3           # Contrast variation range
  temporal_dropout_prob: 0.1    # Temporal frame dropout
  noise_std: 0.05               # Gaussian noise standard deviation
model:
  model_name: "facebook/timesformer-base-finetuned-k400"

# Anti-overfitting experiment configurations
experiments:
  default:
    description: "Default configuration with regularization"
    learning_rate: 0.0001
    num_frames: 8
    sampling_rate: 32
    batch_size: 4
    epochs: 15
    weight_decay: 0.01
  
  high_regularization:
    description: "High regularization to combat overfitting"
    learning_rate: 0.0001
    num_frames: 8
    sampling_rate: 32
    batch_size: 4
    epochs: 20
    weight_decay: 0.05
  
  low_lr_regularized:
    description: "Lower learning rate with regularization"
    learning_rate: 0.00005
    num_frames: 8
    sampling_rate: 32
    batch_size: 4
    epochs: 25
    weight_decay: 0.01
  
  more_frames_regularized:
    description: "More frames with regularization"
    learning_rate: 0.0001
    num_frames: 16
    sampling_rate: 16
    batch_size: 2
    epochs: 20
    weight_decay: 0.02
  
  conservative_training:
    description: "Conservative training to prevent overfitting"
    learning_rate: 0.00003
    num_frames: 6
    sampling_rate: 40
    batch_size: 6
    epochs: 30
    weight_decay: 0.03
